#                 Model persistence
## saving and loading Machine Learning Models using Python's built-in persistence model, namely pickle.  And Joblib in specific case of sciKit-learn which is more efficient on objects that carry computations on large  numpy array

In [13]:
from sklearn import datasets
import numpy as np
from sklearn import linear_model
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC

In [14]:
df = pd.read_csv('C:\\Users\\kunda\\Documents\\project\\price.csv')

In [15]:
df

Area   Prices
0  2600  1008000
1  2700  2000000
2  2900  4000000
3  3100  4500000
4  3400  5000000
5  3500  5100000
6  3550  5300000
7  3600  5333000
8  4000  7250000

In [16]:
model = linear_model.LinearRegression()
model.fit(df[['Area']],df.Prices)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
model.coef_

array([3846.43637532])

In [18]:
model.intercept_

-8155767.5128534725

In [19]:
model.predict(4500)

array([9153196.17609254])

# Saving model to a file using python pickle 

In [20]:
import pickle

In [22]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

# Now loading saved nodel into memory 'mem'

In [37]:
with open('model_pickle','rb') as f:
    mem_pick = pickle.load(f)

# Now predicting the home prices using the saved model

In [38]:
mem_pick.coef_

array([3846.43637532])

In [39]:
mem_pick.intercept_

-8155767.5128534725

In [40]:
mem_pick.predict

<bound method LinearModel.predict of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)>

In [41]:
# same answer it will give
mem_pick.predict(4500)

array([9153196.17609254])

# Saving Trained Model Using joblib

In [30]:
from sklearn.externals import joblib

In [31]:
joblib.dump(model,'model_joblib')

['model_joblib']

# Load saved model from memory

In [32]:
mem_job = joblib.load('model_joblib')

In [33]:
mem_job.coef_

array([3846.43637532])

In [34]:
mem_job.intercept_

-8155767.5128534725

In [35]:
mem_job.predict(4500)

array([9153196.17609254])

In [36]:
print(mem_job.predict(4500))

[9153196.17609254]
